package pojos;
// Generated 09-may-2018 19:00:27 by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Alumnos generated by hbm2java
 */
public class Alumnos implements java.io.Serializable {

	private String dni;
	private Aula aula;
	private String nombre;
	private String apellidos;
	private String email;
	private Set<Asistencia> asistencias = new HashSet<Asistencia>(0);
	private Set<Matricula> matriculas = new HashSet<Matricula>(0);

	public Alumnos() {
	}

	public Alumnos(String dni, Aula aula, String nombre, String apellidos, String email) {
		this.dni = dni;
		this.aula = aula;
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.email = email;
	}

	public Alumnos(String dni, Aula aula, String nombre, String apellidos, String email, Set<Asistencia> asistencias,
			Set<Matricula> matriculas) {
		this.dni = dni;
		this.aula = aula;
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.email = email;
		this.asistencias = asistencias;
		this.matriculas = matriculas;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public Aula getAula() {
		return this.aula;
	}

	public void setAula(Aula aula) {
		this.aula = aula;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Set<Asistencia> getAsistencias() {
		return this.asistencias;
	}

	public void setAsistencias(Set<Asistencia> asistencias) {
		this.asistencias = asistencias;
	}

	public Set<Matricula> getMatriculas() {
		return this.matriculas;
	}

	public void setMatriculas(Set<Matricula> matriculas) {
		this.matriculas = matriculas;
	}

}
