package pojos;
// Generated 09-may-2018 19:00:27 by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Asignatura generated by hbm2java
 */
public class Asignatura implements java.io.Serializable {

	private int idAsignatura;
	private String nombreAsignatura;
	private Set<Unidadformativa> unidadformativas = new HashSet<Unidadformativa>(0);

	public Asignatura() {
	}

	public Asignatura(int idAsignatura, String nombreAsignatura) {
		this.idAsignatura = idAsignatura;
		this.nombreAsignatura = nombreAsignatura;
	}

	public Asignatura(int idAsignatura, String nombreAsignatura, Set<Unidadformativa> unidadformativas) {
		this.idAsignatura = idAsignatura;
		this.nombreAsignatura = nombreAsignatura;
		this.unidadformativas = unidadformativas;
	}

	public Asignatura(int idAsignatura2) {
		this.idAsignatura=idAsignatura2;
	}

	public int getIdAsignatura() {
		return this.idAsignatura;
	}

	public void setIdAsignatura(int idAsignatura) {
		this.idAsignatura = idAsignatura;
	}

	public String getNombreAsignatura() {
		return this.nombreAsignatura;
	}

	public void setNombreAsignatura(String nombreAsignatura) {
		this.nombreAsignatura = nombreAsignatura;
	}

	public Set<Unidadformativa> getUnidadformativas() {
		return this.unidadformativas;
	}

	public void setUnidadformativas(Set<Unidadformativa> unidadformativas) {
		this.unidadformativas = unidadformativas;
	}

}
