package pojos;
// Generated 25/05/2018 16:43:07 by Hibernate Tools 4.0.1.Final

/**
 * AsistenciaId generated by hbm2java
 */
public class AsistenciaId implements java.io.Serializable {

	private String dniAlumno;
	private int idUnidadFormativa;
	private int idFranja;
	private String fecha;

	public AsistenciaId() {
	}

	public AsistenciaId(String dniAlumno, int idUnidadFormativa, int idFranja, String fecha) {
		this.dniAlumno = dniAlumno;
		this.idUnidadFormativa = idUnidadFormativa;
		this.idFranja = idFranja;
		this.fecha = fecha;
	}

	public String getDniAlumno() {
		return this.dniAlumno;
	}

	public void setDniAlumno(String dniAlumno) {
		this.dniAlumno = dniAlumno;
	}

	public int getIdUnidadFormativa() {
		return this.idUnidadFormativa;
	}

	public void setIdUnidadFormativa(int idUnidadFormativa) {
		this.idUnidadFormativa = idUnidadFormativa;
	}

	public int getIdFranja() {
		return this.idFranja;
	}

	public void setIdFranja(int idFranja) {
		this.idFranja = idFranja;
	}

	public String getFecha() {
		return this.fecha;
	}

	public void setFecha(String fecha) {
		this.fecha = fecha;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AsistenciaId))
			return false;
		AsistenciaId castOther = (AsistenciaId) other;

		return ((this.getDniAlumno() == castOther.getDniAlumno()) || (this.getDniAlumno() != null
				&& castOther.getDniAlumno() != null && this.getDniAlumno().equals(castOther.getDniAlumno())))
				&& (this.getIdUnidadFormativa() == castOther.getIdUnidadFormativa())
				&& (this.getIdFranja() == castOther.getIdFranja())
				&& ((this.getFecha() == castOther.getFecha()) || (this.getFecha() != null
						&& castOther.getFecha() != null && this.getFecha().equals(castOther.getFecha())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getDniAlumno() == null ? 0 : this.getDniAlumno().hashCode());
		result = 37 * result + this.getIdUnidadFormativa();
		result = 37 * result + this.getIdFranja();
		result = 37 * result + (getFecha() == null ? 0 : this.getFecha().hashCode());
		return result;
	}

}
