package pojos;
// Generated 22-may-2018 18:23:59 by Hibernate Tools 4.0.1.Final

/**
 * AsistenciaId generated by hbm2java
 */
public class AsistenciaId implements java.io.Serializable {

	private String dniAlumno;
	private int idUnidadFormativa;
	private String idFranja;

	public AsistenciaId() {
	}

	public AsistenciaId(String dniAlumno, int idUnidadFormativa, String idFranja) {
		this.dniAlumno = dniAlumno;
		this.idUnidadFormativa = idUnidadFormativa;
		this.idFranja = idFranja;
	}

	public String getDniAlumno() {
		return this.dniAlumno;
	}

	public void setDniAlumno(String dniAlumno) {
		this.dniAlumno = dniAlumno;
	}

	public int getIdUnidadFormativa() {
		return this.idUnidadFormativa;
	}

	public void setIdUnidadFormativa(int idUnidadFormativa) {
		this.idUnidadFormativa = idUnidadFormativa;
	}

	public String getIdFranja() {
		return this.idFranja;
	}

	public void setIdFranja(String idFranja) {
		this.idFranja = idFranja;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AsistenciaId))
			return false;
		AsistenciaId castOther = (AsistenciaId) other;

		return ((this.getDniAlumno() == castOther.getDniAlumno()) || (this.getDniAlumno() != null
				&& castOther.getDniAlumno() != null && this.getDniAlumno().equals(castOther.getDniAlumno())))
				&& (this.getIdUnidadFormativa() == castOther.getIdUnidadFormativa())
				&& ((this.getIdFranja() == castOther.getIdFranja()) || (this.getIdFranja() != null
						&& castOther.getIdFranja() != null && this.getIdFranja().equals(castOther.getIdFranja())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getDniAlumno() == null ? 0 : this.getDniAlumno().hashCode());
		result = 37 * result + this.getIdUnidadFormativa();
		result = 37 * result + (getIdFranja() == null ? 0 : this.getIdFranja().hashCode());
		return result;
	}

}
