package pojos;
// Generated 22-may-2018 18:23:59 by Hibernate Tools 4.0.1.Final

/**
 * Asistencia generated by hbm2java
 */
public class Asistencia implements java.io.Serializable {

	private AsistenciaId id;
	private Alumnos alumnos;
	private Franjas franjas;
	private Unidadformativa unidadformativa;
	private boolean justificante;
	private String fecha;

	public Asistencia() {
	}

	public Asistencia(AsistenciaId id, Alumnos alumnos, Franjas franjas, Unidadformativa unidadformativa,
			boolean justificante, String fecha) {
		this.id = id;
		this.alumnos = alumnos;
		this.franjas = franjas;
		this.unidadformativa = unidadformativa;
		this.justificante = justificante;
		this.fecha = fecha;
	}

	public AsistenciaId getId() {
		return this.id;
	}

	public void setId(AsistenciaId id) {
		this.id = id;
	}

	public Alumnos getAlumnos() {
		return this.alumnos;
	}

	public void setAlumnos(Alumnos alumnos) {
		this.alumnos = alumnos;
	}

	public Franjas getFranjas() {
		return this.franjas;
	}

	public void setFranjas(Franjas franjas) {
		this.franjas = franjas;
	}

	public Unidadformativa getUnidadformativa() {
		return this.unidadformativa;
	}

	public void setUnidadformativa(Unidadformativa unidadformativa) {
		this.unidadformativa = unidadformativa;
	}

	public boolean isJustificante() {
		return this.justificante;
	}

	public void setJustificante(boolean justificante) {
		this.justificante = justificante;
	}

	public String getFecha() {
		return fecha;
	}

	public void setFecha(String fecha) {
		this.fecha = fecha;
	}


}
