package pojos;
// Generated 09-may-2018 19:00:27 by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Aula generated by hbm2java
 */
public class Aula implements java.io.Serializable {

	private int numAula;
	private Set<Alumnos> alumnoses = new HashSet<Alumnos>(0);

	public Aula() {
	}

	public Aula(int numAula) {
		this.numAula = numAula;
	}

	public Aula(int numAula, Set<Alumnos> alumnoses) {
		this.numAula = numAula;
		this.alumnoses = alumnoses;
	}

	public int getNumAula() {
		return this.numAula;
	}

	public void setNumAula(int numAula) {
		this.numAula = numAula;
	}

	public Set<Alumnos> getAlumnoses() {
		return this.alumnoses;
	}

	public void setAlumnoses(Set<Alumnos> alumnoses) {
		this.alumnoses = alumnoses;
	}

}
