package pojos;
// Generated 30/05/2018 19:29:46 by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Ciclo generated by hbm2java
 */
public class Ciclo implements java.io.Serializable {

	private int idCiclo;
	private String nombreCiclo;
	private Set<Asignatura> asignaturas = new HashSet<Asignatura>(0);

	public Ciclo() {
	}

	public Ciclo(int idCiclo, String nombreCiclo) {
		this.idCiclo = idCiclo;
		this.nombreCiclo = nombreCiclo;
	}

	public Ciclo(int idCiclo, String nombreCiclo, Set<Asignatura> asignaturas) {
		this.idCiclo = idCiclo;
		this.nombreCiclo = nombreCiclo;
		this.asignaturas = asignaturas;
	}

	public int getIdCiclo() {
		return this.idCiclo;
	}

	public void setIdCiclo(int idCiclo) {
		this.idCiclo = idCiclo;
	}

	public String getNombreCiclo() {
		return this.nombreCiclo;
	}

	public void setNombreCiclo(String nombreCiclo) {
		this.nombreCiclo = nombreCiclo;
	}

	public Set<Asignatura> getAsignaturas() {
		return this.asignaturas;
	}

	public void setAsignaturas(Set<Asignatura> asignaturas) {
		this.asignaturas = asignaturas;
	}
	 @Override
	    public String toString() {
	        return this.nombreCiclo;
}
}
