package pojos;
// Generated 25/05/2018 16:43:07 by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Franjas generated by hbm2java
 */
public class Franjas implements java.io.Serializable {

	private int idFranja;
	private Horas horas;
	private Asignatura asignatura;
	private Profesor profesor;
	private String dia;
	private Set<Asistencia> asistencias = new HashSet<Asistencia>(0);

	public Franjas() {
	}

	public Franjas(int idFranja, Horas horas, Asignatura asignatura, Profesor profesor, String dia) {
		this.idFranja = idFranja;
		this.horas = horas;
		this.asignatura = asignatura;
		this.profesor = profesor;
		this.dia = dia;
	}

	public Franjas(int idFranja, Horas horas, Asignatura asignatura, Profesor profesor, String dia,
			Set<Asistencia> asistencias) {
		this.idFranja = idFranja;
		this.horas = horas;
		this.asignatura = asignatura;
		this.profesor = profesor;
		this.dia = dia;
		this.asistencias = asistencias;
	}

	public int getIdFranja() {
		return this.idFranja;
	}

	public void setIdFranja(int idFranja) {
		this.idFranja = idFranja;
	}

	public Horas getHoras() {
		return this.horas;
	}

	public void setHoras(Horas horas) {
		this.horas = horas;
	}

	public Asignatura getAsignatura() {
		return this.asignatura;
	}

	public void setAsignatura(Asignatura asignatura) {
		this.asignatura = asignatura;
	}

	public Profesor getProfesor() {
		return this.profesor;
	}

	public void setProfesor(Profesor profesor) {
		this.profesor = profesor;
	}

	public String getDia() {
		return this.dia;
	}

	public void setDia(String dia) {
		this.dia = dia;
	}

	public Set<Asistencia> getAsistencias() {
		return this.asistencias;
	}

	public void setAsistencias(Set<Asistencia> asistencias) {
		this.asistencias = asistencias;
	}

}
