package pojos;
// Generated 09-may-2018 19:00:27 by Hibernate Tools 4.0.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Franjas generated by hbm2java
 */
public class Franjas implements java.io.Serializable {

	private String idFranja;
	private Profesor profesor;
	private Date horaInicio;
	private Date horaFin;
	private String dia;
	private Set<Asistencia> asistencias = new HashSet<Asistencia>(0);

	public Franjas() {
	}

	public Franjas(String idFranja, Profesor profesor, Date horaInicio, Date horaFin, String dia) {
		this.idFranja = idFranja;
		this.profesor = profesor;
		this.horaInicio = horaInicio;
		this.horaFin = horaFin;
		this.dia = dia;
	}

	public Franjas(String idFranja, Profesor profesor, Date horaInicio, Date horaFin, String dia,
			Set<Asistencia> asistencias) {
		this.idFranja = idFranja;
		this.profesor = profesor;
		this.horaInicio = horaInicio;
		this.horaFin = horaFin;
		this.dia = dia;
		this.asistencias = asistencias;
	}

	public Franjas(String idFranja2) {
		this.idFranja = idFranja2;
	}

	public String getIdFranja() {
		return this.idFranja;
	}

	public void setIdFranja(String idFranja) {
		this.idFranja = idFranja;
	}

	public Profesor getProfesor() {
		return this.profesor;
	}

	public void setProfesor(Profesor profesor) {
		this.profesor = profesor;
	}

	public Date getHoraInicio() {
		return this.horaInicio;
	}

	public void setHoraInicio(Date horaInicio) {
		this.horaInicio = horaInicio;
	}

	public Date getHoraFin() {
		return this.horaFin;
	}

	public void setHoraFin(Date horaFin) {
		this.horaFin = horaFin;
	}

	public String getDia() {
		return this.dia;
	}

	public void setDia(String dia) {
		this.dia = dia;
	}

	public Set<Asistencia> getAsistencias() {
		return this.asistencias;
	}

	public void setAsistencias(Set<Asistencia> asistencias) {
		this.asistencias = asistencias;
	}

}
