package pojos;
// Generated 25/05/2018 16:43:07 by Hibernate Tools 4.0.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Horas generated by hbm2java
 */
public class Horas implements java.io.Serializable {

	private int idHoras;
	private Date horaInicio;
	private Date horaFin;
	private Set<Franjas> franjases = new HashSet<Franjas>(0);

	public Horas() {
	}

	public Horas(int idHoras) {
		this.idHoras = idHoras;
	}

	public Horas(int idHoras, Date horaInicio, Date horaFin, Set<Franjas> franjases) {
		this.idHoras = idHoras;
		this.horaInicio = horaInicio;
		this.horaFin = horaFin;
		this.franjases = franjases;
	}

	public int getIdHoras() {
		return this.idHoras;
	}

	public void setIdHoras(int idHoras) {
		this.idHoras = idHoras;
	}

	public Date getHoraInicio() {
		return this.horaInicio;
	}

	public void setHoraInicio(Date horaInicio) {
		this.horaInicio = horaInicio;
	}

	public Date getHoraFin() {
		return this.horaFin;
	}

	public void setHoraFin(Date horaFin) {
		this.horaFin = horaFin;
	}

	public Set<Franjas> getFranjases() {
		return this.franjases;
	}

	public void setFranjases(Set<Franjas> franjases) {
		this.franjases = franjases;
	}
	@Override
	public String toString() {
		return horaInicio+ " / " + horaFin;
	}


}
