package pojos;
// Generated 22-may-2018 18:23:59 by Hibernate Tools 4.0.1.Final

/**
 * MatriculaId generated by hbm2java
 */
public class MatriculaId implements java.io.Serializable {

	private String dniAlumno;
	private int idUnidadFormativa;

	public MatriculaId() {
	}

	public MatriculaId(String dniAlumno, int idUnidadFormativa) {
		this.dniAlumno = dniAlumno;
		this.idUnidadFormativa = idUnidadFormativa;
	}

	public String getDniAlumno() {
		return this.dniAlumno;
	}

	public void setDniAlumno(String dniAlumno) {
		this.dniAlumno = dniAlumno;
	}

	public int getIdUnidadFormativa() {
		return this.idUnidadFormativa;
	}

	public void setIdUnidadFormativa(int idUnidadFormativa) {
		this.idUnidadFormativa = idUnidadFormativa;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MatriculaId))
			return false;
		MatriculaId castOther = (MatriculaId) other;

		return ((this.getDniAlumno() == castOther.getDniAlumno()) || (this.getDniAlumno() != null
				&& castOther.getDniAlumno() != null && this.getDniAlumno().equals(castOther.getDniAlumno())))
				&& (this.getIdUnidadFormativa() == castOther.getIdUnidadFormativa());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getDniAlumno() == null ? 0 : this.getDniAlumno().hashCode());
		result = 37 * result + this.getIdUnidadFormativa();
		return result;
	}

}
