package pojos;
// Generated 09-may-2018 19:00:27 by Hibernate Tools 4.0.1.Final

/**
 * MatriculaId generated by hbm2java
 */
public class MatriculaId implements java.io.Serializable {

	private String dniAlumno;
	private String idUnidadFormativa;

	public MatriculaId() {
	}

	public MatriculaId(String dniAlumno, String idUnidadFormativa) {
		this.dniAlumno = dniAlumno;
		this.idUnidadFormativa = idUnidadFormativa;
	}

	public String getDniAlumno() {
		return this.dniAlumno;
	}

	public void setDniAlumno(String dniAlumno) {
		this.dniAlumno = dniAlumno;
	}

	public String getIdUnidadFormativa() {
		return this.idUnidadFormativa;
	}

	public void setIdUnidadFormativa(String idUnidadFormativa) {
		this.idUnidadFormativa = idUnidadFormativa;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MatriculaId))
			return false;
		MatriculaId castOther = (MatriculaId) other;

		return ((this.getDniAlumno() == castOther.getDniAlumno()) || (this.getDniAlumno() != null
				&& castOther.getDniAlumno() != null && this.getDniAlumno().equals(castOther.getDniAlumno())))
				&& ((this.getIdUnidadFormativa() == castOther.getIdUnidadFormativa())
						|| (this.getIdUnidadFormativa() != null && castOther.getIdUnidadFormativa() != null
								&& this.getIdUnidadFormativa().equals(castOther.getIdUnidadFormativa())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getDniAlumno() == null ? 0 : this.getDniAlumno().hashCode());
		result = 37 * result + (getIdUnidadFormativa() == null ? 0 : this.getIdUnidadFormativa().hashCode());
		return result;
	}

}
