package pojos;
// Generated 09-may-2018 19:00:27 by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Profesor generated by hbm2java
 */
public class Profesor implements java.io.Serializable {

	private String dniProfesor;
	private String nombre;
	private String idUnidadFormativa;
	private String usuari;
	private String password;
	private Set<Unidadformativa> unidadformativas = new HashSet<Unidadformativa>(0);
	private Set<Franjas> franjases = new HashSet<Franjas>(0);

	public Profesor() {
	}

	public Profesor(String dniProfesor, String nombre, String idUnidadFormativa, String usuari, String password) {
		this.dniProfesor = dniProfesor;
		this.nombre = nombre;
		this.idUnidadFormativa = idUnidadFormativa;
		this.usuari = usuari;
		this.password = password;
	}

	public Profesor(String dniProfesor, String nombre, String idUnidadFormativa, String usuari, String password,
			Set<Unidadformativa> unidadformativas, Set<Franjas> franjases) {
		this.dniProfesor = dniProfesor;
		this.nombre = nombre;
		this.idUnidadFormativa = idUnidadFormativa;
		this.usuari = usuari;
		this.password = password;
		this.unidadformativas = unidadformativas;
		this.franjases = franjases;
	}

	public String getDniProfesor() {
		return this.dniProfesor;
	}

	public void setDniProfesor(String dniProfesor) {
		this.dniProfesor = dniProfesor;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getIdUnidadFormativa() {
		return this.idUnidadFormativa;
	}

	public void setIdUnidadFormativa(String idUnidadFormativa) {
		this.idUnidadFormativa = idUnidadFormativa;
	}

	public String getUsuari() {
		return this.usuari;
	}

	public void setUsuari(String usuari) {
		this.usuari = usuari;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Set<Unidadformativa> getUnidadformativas() {
		return this.unidadformativas;
	}

	public void setUnidadformativas(Set<Unidadformativa> unidadformativas) {
		this.unidadformativas = unidadformativas;
	}

	public Set<Franjas> getFranjases() {
		return this.franjases;
	}

	public void setFranjases(Set<Franjas> franjases) {
		this.franjases = franjases;
	}

}
